# -*- coding: utf-8 -*-
"""Spotify_Music_Trends_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDe7dqOpy6WWJHUPV9E_2HnTNoWW7tD2
"""

from google.colab import files
uploaded = files.upload()

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io
import zipfile

# Load Dataset
# The uploaded file is a zip file, so we need to extract the CSV from it.
zip_file = zipfile.ZipFile(io.BytesIO(uploaded['SpotifyFeatures.csv.zip']))
df = pd.read_csv(zip_file.open('SpotifyFeatures.csv'))

# Display first rows
print(df.head())

# Dataset Info
print(df.info())

# Statistical Summary
print(df.describe())

# Missing Values
print(df.isnull().sum())

# Duplicate Values
print("Duplicates:", df.duplicated().sum())

# Remove duplicates
df.drop_duplicates(inplace=True)

# -------------------------------
# VISUALIZATION 1
# Genre Distribution
# -------------------------------
plt.figure(figsize=(12,6))
df['genre'].value_counts().head(10).plot(kind='bar')
plt.title("Top 10 Genres")
plt.xlabel("Genre")
plt.ylabel("Count")
plt.show()

# -------------------------------
# VISUALIZATION 2
# Popularity Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.histplot(df['popularity'], bins=30, kde=True)
plt.title("Popularity Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 3
# Danceability Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.histplot(df['danceability'], kde=True)
plt.title("Danceability Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 4
# Energy vs Popularity
# -------------------------------
plt.figure(figsize=(10,6))
sns.scatterplot(x='energy', y='popularity', data=df)
plt.title("Energy vs Popularity")
plt.show()

# -------------------------------
# VISUALIZATION 5
# Loudness Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.boxplot(x=df['loudness'])
plt.title("Loudness Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 6
# Tempo Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.histplot(df['tempo'], bins=30)
plt.title("Tempo Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 7
# Acousticness vs Popularity
# -------------------------------
plt.figure(figsize=(10,6))
sns.scatterplot(x='acousticness', y='popularity', data=df)
plt.title("Acousticness vs Popularity")
plt.show()

# -------------------------------
# VISUALIZATION 8
# Valence Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.histplot(df['valence'], kde=True)
plt.title("Valence Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 9
# Correlation Heatmap
# -------------------------------
plt.figure(figsize=(14,10))
corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# -------------------------------
# VISUALIZATION 10
# Top Artists
# -------------------------------
plt.figure(figsize=(12,6))
df['artist_name'].value_counts().head(10).plot(kind='bar')
plt.title("Top 10 Artists")
plt.show()

# -------------------------------
# VISUALIZATION 11
# Instrumentalness Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.histplot(df['instrumentalness'], kde=True)
plt.title("Instrumentalness Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 12
# Speechiness Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.histplot(df['speechiness'], kde=True)
plt.title("Speechiness Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 13
# Liveness Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.histplot(df['liveness'], kde=True)
plt.title("Liveness Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 14
# Duration Distribution
# -------------------------------
plt.figure(figsize=(10,5))
sns.histplot(df['duration_ms'], bins=40)
plt.title("Song Duration Distribution")
plt.show()

# -------------------------------
# VISUALIZATION 15
# Explicit Songs Count
# -------------------------------
top_genres = df['genre'].value_counts().head(5)

plt.figure(figsize=(8,8))

plt.pie(top_genres, labels=top_genres.index, autopct='%1.1f%%')

plt.title("Top 5 Genres Share")

plt.show()
print("EDA Completed Successfully!")